#!/bin/bash
set -e

localNpm() { (PATH=$(npm bin):$PATH; eval $@; ) }

case $1 in
  "karma")
    if [[ $2 == "--once" ]] || [[ $2 == "-o" ]]; then
      localNpm karma start --single-run
    else
      localNpm karma start
    fi
  ;;
  "test")
      if [[ $2 == "--watch" ]] || [[ $2 == "-w" ]]; then
        localNpm mocha --colors --watch
      elif [[ $2 == "--ci" ]] || [[ $2 == "-c" ]]; then
        localNpm mocha --colors --check-leaks --slow 10
      else
        localNpm mocha --colors
      fi
  ;;
  "server") localNpm webpack-dev-server
  ;;
  *) echo "Not a valid command"
esac
